<?xml version="1.0" encoding="UTF-8"?>

<!-- St. Gall Stylesheet for the Expanded Contents page of a work within a manuscript-->
<!-- edited by Richard Pollard to include bibliography 10/2010 -->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0"
    xmlns:tei="http://www.tei-c.org/ns/1.0">
   
   <xsl:include href="TEISubWorkBibliography.xsl" />
   <xsl:include href="TEIWorkSubContents.xsl" />
    <!-- line below only used for testing 
        <xsl:param name="count" select="4"/>  -->
    <!--xsl:include href="TEIBibliography.xsl" /-->
    <xsl:output method="html" />
    <xsl:template match="/" name="generateWorkContent">
	 <xsl:param name="count" />

       
			
           
			<div class="stgall-flex-container">
		    <div class="stgall-work-title">
		       <!-- Contents for left view frame copy paste the DIV tag section to add more
                    content.
    The page numbers to the right are under span tags--><span> [                    <xsl:value-of select="$count" />
]                    
                        <xsl:value-of select="tei:locus" />
                    </span>
         <span>:                 
			 
                        <xsl:value-of select="tei:title" />
                    </span>

                    <br />
		   	 </div>
			
          
              

                    


                    <div class="stgall-contents">
                        <br />
                        <!--<img src="images/icon_content.jpg" width="20" height="20" alt="Content" />:-->
						
                       		                     <!-- Book-Level -->
                                <xsl:for-each select="tei:msItem">
                                    <xsl:if test="tei:workGroupHeading">
										<div class="work-group-heading">
                                        <p>
                                            <h4>[                                                <b>
                                                    <xsl:value-of select="tei:workGroupHeading/tei:locus" />
                                                </b>
        ]                                                <xsl:choose>
                                                    <xsl:when test="tei:workGroupHeading/tei:title">

                                                        <xsl:value-of select="tei:workGroupHeading/tei:title" />

                                                    </xsl:when>

                                                    <xsl:otherwise>
                                                        <xsl:value-of select="tei:workGroupHeading/tei:rubric" />
                                                    </xsl:otherwise>
                                                </xsl:choose>

                                            </h4>
                                        </p>
                                        </div>
                                    </xsl:if>

                                    <div class="stgall-work-item">
										<div class="stgall-work-item-heading">

                                        <xsl:value-of select="$count" />.<xsl:value-of select="position()" />
                                    <xsl:text></xsl:text>



                                    <xsl:choose>

                                        <xsl:when test="tei:title">
                                            <!-- TODO what should be link  -->
                                            <!-- href="/stgallmss/viewItem.do?count={@n}&amp;pageArk={tei:locus/@facs}&amp;fileId={$fileId}"-->
                                            <a target="_top">
                                                <xsl:value-of select="tei:title" />
                                            </a>                                            <!--
                                                This link should take the user to the Contents page
                                                for the work (generated by workcontents.xsl) -->

                                        </xsl:when>
                                        <xsl:otherwise>
                                            <!-- TODO LINK href="/stgallmss/viewItem.do?xmlstylesheet=TEITranscription.xsl&amp;count={@n}&amp;ark={tei:locus/@facs}&amp;fileId={$fileId}" -->
                                            <a target="_top">
                                                <xsl:value-of select="tei:rubric" />
                                            </a>
                                        </xsl:otherwise>

                                    </xsl:choose>
                                    <span
                                           >
                                            &#160; <xsl:value-of select="tei:locus" />
                                    </span>
                                    </div>
                                    <dl class="document-metadata document__list-metadata-group">
                                        <xsl:choose>
                                            <xsl:when test="tei:rubric">

                                                <dl class="document__list-metadata-key document__list-metadata-key--ursus blacklight-date_created_tesim">
                                                   Rubric:  </dl>
                                                   <dd class="document__list-metadata-value document__list-metadata-value--ursus blacklight-date_created_tesim"> <xsl:value-of select="tei:rubric" /> </dd>
                                               

                                            </xsl:when>
                                            <xsl:otherwise></xsl:otherwise>
                                        </xsl:choose>
                                        <xsl:if test="tei:incipit">
                                            
                                                <dl class="document__list-metadata-key document__list-metadata-key--ursus blacklight-date_created_tesim">Incipit: </dl>
                                                <dd class="document__list-metadata-value document__list-metadata-value--ursus blacklight-date_created_tesim"><xsl:value-of select="tei:incipit" /></dd>
                                            
                                        </xsl:if>
                                        <xsl:if test="tei:explicit">
                                            
                                                <dl class="document__list-metadata-key document__list-metadata-key--ursus blacklight-date_created_tesim">Explicit: </dl>
                                                <dd class="document__list-metadata-value document__list-metadata-value--ursus blacklight-date_created_tesim"><xsl:value-of select="tei:explicit" /></dd>
                                           
                                        </xsl:if>
                                        <xsl:if test="tei:incipit2">
                                           
                                           
                                                <dl class="document__list-metadata-key document__list-metadata-key--ursus blacklight-date_created_tesim">Incipit: </dl>
                                                <dd class="document__list-metadata-value document__list-metadata-value--ursus blacklight-date_created_tesim"><xsl:value-of select="tei:incipit2" /></dd>
                                            
                                        </xsl:if>
                                        <xsl:if test="tei:explicit2">
                                           
                                                <dl class="document__list-metadata-key document__list-metadata-key--ursus blacklight-date_created_tesim">Explicit: </dl>
                                                <dd class="document__list-metadata-value document__list-metadata-value--ursus blacklight-date_created_tesim"><xsl:value-of select="tei:explicit2" /></dd>
                                            
                                        </xsl:if>
                                        <xsl:if test="tei:note">
                                            
                                                <dl class="document__list-metadata-key document__list-metadata-key--ursus blacklight-date_created_tesim">Remarks: </dl>
                                                <dd class="document__list-metadata-value document__list-metadata-value--ursus blacklight-date_created_tesim"><xsl:value-of select="tei:note" /></dd>
                                            
                                        </xsl:if>
                                    </dl>

                                    <xsl:if test="count(tei:listBibl) > 0">
                                        <xsl:if test="count(tei:listBibl/tei:head[. = 'Related Texts'] | tei:listBibl/tei:head[. = 'Bibliography'] | tei:listBibl/tei:head[. = 'Editions']  |  tei:listBibl/tei:head[. = 'Edition']   | tei:listBibl/tei:head[. = 'Edition and Bibliography']  |   tei:listBibl/tei:head[. = 'Translation'])  > 0">
                                            <xsl:if test="count(tei:listBibl/tei:head[. = 'Related Texts'] | tei:listBibl/tei:head[. = 'Bibliography'] | tei:listBibl/tei:head[. = 'Editions'] |  tei:listBibl/tei:head[. = 'Translation'] | tei:listBibl/tei:head[. = 'Edition and Bibliography'] | tei:listBibl/tei:head[. = 'Edition']/following-sibling::tei:biblStruct) > 0">
                                                <!-- href="/stgallmss/viewFile.do?xmlstylesheet=TEISubWorkBibliography.xsl&amp;count={@n}&amp;fileId={$fileId}"-->
                                                <!--a style="" href="javascript:void(0)" onclick="performXSLTTransformation('TEISubWorkBibliography.xsl','{@n}');">
                                                    <img src="../images/icon_bibliography.jpg" width="20" height="20" alt="Bibliography" />
                                                </a-->
                                                <h4>Sub Work Bibliograpghy</h4>
                                                <xsl:text></xsl:text>
                                                <div id="work-item-sub-bibliograghy-{@n}"
													class="stgall-work-item-bibliography">
		
		
													<xsl:call-template
														name="generateSubWorkBibliography">
														<xsl:with-param name="count"
															select="@n" />
													</xsl:call-template>
												</div>
                                            </xsl:if>
                                        </xsl:if>


                                    </xsl:if>
                                    <xsl:if test="count(tei:msItem) > 0">
                                        <!-- /stgallmss/viewItem.do?xmlstylesheet=TEIWorkSubContents.xsl&amp;count={@n}&amp;pageArk={tei:locus/@facs}&amp;fileId={$fileId} -->

                                        <!--a target="_top" style="border-style:none" href="javascript:void(0)" onclick="performXSLTTransformation('TEIWorkSubContents.xsl','{@n}', '{tei:locus/@facs}');">
                                            <img src="../images/icon_content.jpg" width="20" height="20" alt="Content" style="" />
                                        </a-->
                                        <h4>Sub Work Contents</h4>
                                        <xsl:text></xsl:text>
                                        <div id="work-item-sub-content-{@n}"
													class="stgall-work-item-content">
		
		
													<xsl:call-template
														name="generateSubWorkContent">
														<xsl:with-param name="count"
															select="@n" />
													</xsl:call-template>
												</div>
                                        
                                    </xsl:if>
                                    <!-- href="/stgallmss/viewItem.do?xmlstylesheet=TEITranscription.xsl&amp;count={@n}&amp;pageArk={tei:locus/@facs}&amp;fileId={$fileId}" -->
                                    <!--a target="_top" style="" href="javascript:void(0)" onclick="performXSLTTransformation('TEITranscription.xsl','{@n}', '{tei:locus/@facs}');">
                                        <img src="../images/icon_text.jpg" width="20" height="20" alt="Text" style="" />
                                    </a-->
                                    <!--xsl:text></xsl:text>
                                    <h4> Sub Work Transcription</h4>
                                    <div id="work-sub-item-transcription-{@n}"
										class="work-item-transcription ">
										<xsl:call-template
											name="generateWorkTranscription">
											<xsl:with-param name="count"
												select="@n" />
											<xsl:with-param name="ark"
												select="tei:locus/@facs" />
										</xsl:call-template>
									</div-->
                                    <br />
                                </div>


                            </xsl:for-each>
                            <!-- </ul> -->
                      

                </div>

                <!-- Content table for left view frame END-->
                <br />
                <br />
</div>

</xsl:template>

</xsl:stylesheet>